language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angulator' ]; then cd .. && eval "mv $currentfolder generator-angulator" && cd generator-angulator; fi

